  on:
    push:
      branches:
        - master
        - feature/*
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: 11
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn clean install
        - name: Build Docker Image
          uses: actions/upload-artifact@v2
          with:
            name: spring-rest-services
            path: ./
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Archive Docker Image
          uses: actions/upload-artifact@v2
          with:
            name: spring-rest-services
            path: ./
      if: github.ref == 'refs/heads/master'
    feature-deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Archive Docker Image
          uses: actions/upload-artifact@v2
          with:
            name: my-web-app-image
            path: my-web-app.tar
      if: github.ref.startsWith('refs/heads/feature/')
