name: web service deploymnet
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: 'wORKSPACE Environment variable'
  OVER_RIDE: 'Workflow'
on: [push, workflow_dispatch, pull_request]
jobs:
  ubuntu:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'Job Environment variable for first job.'
      OVER_RIDE: 'Job'
    name: ubuntu Job
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        env:
          STEP_ENVIRONMENT_VARIABLE: 'Step Environment Variable for Bash'
          OVER_RIDE: 'STEP'
        uses: actions/checkout@v2
      - name: Step Two
        run: | 
          echo "Accessing environment variables using shell syntax"
          echo "1. $WORKSPACE_ENVIRONMENT_VARIABLE"
          echo "2. $JOB_ENVIRONMENT_VARIABLE"
          echo "3. $STEP_ENVIRONMENT_VARIABLE"
          echo "4. $OVER_RIDE"
          echo ""
          echo "---------------------------------------------------------"
          echo ""
          echo "5. ${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
          echo "6. ${{ env.JOB_ENVIRONMENT_VARIABLE }}"
          echo "7. ${{ env.STEP_ENVIRONMENT_VARIABLE }}"
          echo "8. ${{ env.OVER_RIDE }}"
          echo ""
          echo ""
          env | sort
  windows:
    name: windows Job
    runs-on: windows-latest
    steps: 
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run:  "Get-ChildItem Env: | Sort-Object Name"
  macos:
    name: macos Job
    runs-on: macos-latest
    steps: 
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: |
          sudo su - root
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update
  custom:
    name: custom Job
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps: 
      - name: Step One
        uses: actions/checkout@v2
      - name: Step Two
        run: |
          sudo su - root
          mkdir test    
